services:
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  redis:
    image: redis:7.2.1
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
volumes:
  mysql-data:
  redis-data:
