services:
  mysql:
    image: littlebrownie/calendar-db:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:7.2.1
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 20s
      retries: 30
    volumes:
      - redis-data:/data
  calendar-backend:
    image: littlebrownie/calendar-backend:latest
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1
      timeout: 20s
      retries: 30
  calendar-frontend:
    image: littlebrownie/calendar-frontend:latest
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      timeout: 20s
      retries: 30
    # depends_on:
    #   calendar-backend:
    #     condition: service_healthy
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./letsencrypt:/letsencrypt
      - ./certs:/etc/letsencrypt
    depends_on:
      calendar-backend:
        condition: service_healthy
      calendar-frontend:
        condition: service_healthy
volumes:
  mysql-data:
  redis-data:
