services:
  mysql:
    image: littlebrownie/calendar-db:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:7.2.1
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
    volumes:
      - redis-data:/data
  calendar-backend:
    image: littlebrownie/calendar-backend:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  calendar-frontend:
    image: littlebrownie/calendar-frontend:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      calendar-backend:
        condition: service_started
volumes:
  mysql-data:
  redis-data:
