services:
  mysql:
    image: littlebrownie/calendar-db:latest
    restart: always
  redis:
    image: redis:7.2.1
    restart: always
  calendar-backend:
    image: littlebrownie/calendar-backend:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition:  service_started
      redis:
        condition: service_started
  calendar-frontend:
    image: littlebrownie/calendar-frontend:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      calendar-backend:
        condition: service_started