name: build-backend
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:           
    - name: checkout-files  
      uses: Bhacaz/checkout-files@v2
      with: 
        files: calendar-backend
      # - uses: actions/checkout@v4
      #   with:
      #     sparse-checkout: |
      #       calendar-backend
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn clean install
    