name: build-backend
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: |
          export DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}
          export DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
          cd ./calendar-backend
          mvn clean install
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: "./calendar-backend"
          push: true
          tags: littlebrownie/calendar-backend:latest