name: build-database
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          passowrd: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
          tags: littlebrownie/calendar-db:latest
          build-args: |
            MYSQL_ROOT_PASSWORD=${{ secrets.DATASOURCE_ROOT_PASSWORD }}
            MYSQL_USER=${{ secrets.DATASOURCE_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.DATASOURCE_DATABASE }}
      
